#请求处理的超时时间
ribbon.ReadTimeout: 120000
#请求连接的超时时间
ribbon.ConnectTimeout: 30000


spring: 
  datasource: 
    url: jdbc:mysql://10.10.12.108:3306/mqtest?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false&&useSSL=false
    username: root
    password: Az.123456
    driver-class-name: com.mysql.jdbc.Driver


mybatis: 
  mapper-locations: MytableMapper.xml 
  type-aliases-package: demo.mapper